### ISSUE TITLE
Cannot check properties Azure resource properties from azurerm_virtual_machine

### ISSUE THREAD

**Issue by marcomancuso** [inspec/inspec-azure#106]
### 🎛 Description

🐛 bug report

I am expecting this control to work:
```
control 'azure_virtual_machine' do
  impact 0.7
  title 'Azure VM check'
  describe azurerm_virtual_machine(resource_group: 'my_rg', name: 'host') do
    its('properties.storageProfile.imageReference.publisher') { should eq "OpenLogic" }
  end
end
```
but I actually get:
```
  ×  test: 'host' Virtual Machine
     ×  'host' Virtual Machine properties.storageProfile.imageReference.publisher
     undefined method `storageProfile' for #<Hash:0x000055d22eaf45c8>
```

### 🌍 InSpec and Platform Version

Inspec Version: 2.2.50
ruby 2.5.1p57
Tried both locally on my Mac OS 10.13.6 and on the official inspec docker image Alpine Linux v3.7

### 🤔 Replication Case

- Setup Environment Azure credentials 
- Create an inspec profile
- use the following control:
```
control 'azure_virtual_machine' do
  impact 0.7
  title 'Azure VM check'
  describe azurerm_virtual_machine(resource_group: 'my_rg', name: 'host') do
    its('properties.storageProfile.imageReference.publisher') { should eq "OpenLogic" }
  end
end
```
in inspec.yml:
```
name: azure-create-virtualmachine
title: InSpec Profile
maintainer: The Authors
copyright: The Authors
copyright_email: you@example.com
license: Apache-2.0
summary: An InSpec Compliance Profile
version: 0.1.0
inspec_version: '>= 2.2.7'
depends:
  - name: inspec-azure
    git: https://github.com/inspec/inspec-azure.git
supports:
  - platform: azure
```

run `inspec exec . -t azure://`

### 💁 Possible Solutions

N/A

### 💻 Stacktrace

N/A
