### ISSUE TITLE
undefined method `networkSecurityGroup' for #<#<Class:0x00000004337e18>:0x00000004336298>

### ISSUE THREAD

**Issue by rdtechie** [inspec/inspec-azure#144]
### 🎛 Description

**🐛 bug report**

When I'm using the azurerm_subnet resource and check for NSG presence, I'm getting a error message when there's no NSG attached:

`undefined method 'networkSecurityGroup' for #<#<Class:0x00000004337e18>:0x00000004336298>`

The complete output is as following:
```
[DEPRECATED] use a specific azure resources instead of 'azure_generic_resource'. See https://github.com/inspec/inspec/issues/3131

Profile: InSpec Profile (azure-compliance-profile)
Version: 0.1.0
Target:  azure://af9f0308-1806-444b-9d9e-e10bda0f9aa5

  ✔  check-if-resource-group-exists: Ensure Resource Group Exists
     ✔  Resource Groups with name == "TestNetwork" should exist
  ✔  check-resource-group-properties: Ensure Resource Group properties are correct
     ✔  azure_generic_resource should have tags
     ✔  azure_generic_resource location should eq "northeurope"
     ✔  azure_generic_resource tag_count should equal 2
  ×  azurerm_subnet: 'TestSubnet' subnet (1 failed)
     ✔  'TestSubnet' subnet should exist
     ✔  'TestSubnet' subnet name should eq "TestSubnet"
     ✔  'TestSubnet' subnet type should eq "Microsoft.Network/virtualNetworks/subnets"
     ✔  'TestSubnet' subnet address_prefix should eq "10.10.10.0/24"
     ×  'TestSubnet' subnet nsg
     undefined method `networkSecurityGroup' for #<#<Class:0x00000002a88458>:0x00000002a83b60>


Profile: Azure Resource Pack (inspec-azure)
Version: 1.2.0
Target:  azure://af9f0308-1806-444b-9d9e-e10bda0f9aa5

     No tests executed.

Profile Summary: 2 successful controls, 1 control failure, 0 controls skipped
Test Summary: 8 successful, 1 failure, 0 skipped
```
When I attach the NSG to the subnet, the test completes succesful:
```
[DEPRECATED] use a specific azure resources instead of 'azure_generic_resource'. See https://github.com/inspec/inspec/issues/3131

Profile: InSpec Profile (azure-compliance-profile)
Version: 0.1.0
Target:  azure://af9f0308-1806-444b-9d9e-e10bda0f9aa5

  ✔  check-if-resource-group-exists: Ensure Resource Group Exists
     ✔  Resource Groups with name == "TestNetwork" should exist
  ✔  check-resource-group-properties: Ensure Resource Group properties are correct
     ✔  azure_generic_resource should have tags
     ✔  azure_generic_resource location should eq "northeurope"
     ✔  azure_generic_resource tag_count should equal 2
  ✔  azurerm_subnet: 'TestSubnet' subnet
     ✔  'TestSubnet' subnet should exist
     ✔  'TestSubnet' subnet name should eq "TestSubnet"
     ✔  'TestSubnet' subnet type should eq "Microsoft.Network/virtualNetworks/subnets"
     ✔  'TestSubnet' subnet address_prefix should eq "10.10.10.0/24"
     ✔  'TestSubnet' subnet nsg should eq "TestNsg"


Profile: Azure Resource Pack (inspec-azure)
Version: 1.2.0
Target:  azure://af9f0308-1806-444b-9d9e-e10bda0f9aa5

     No tests executed.

Profile Summary: 3 successful controls, 0 control failures, 0 controls skipped
Test Summary: 9 successful, 0 failures, 0 skipped
```

I'd expect that InSpec would return me a message that there's no NSG attached instead of the message above.

### 🌍 InSpec and Platform Version
```
vmadmin@ubuntu01:/$ inspec version
2.3.5
```
```
vmadmin@ubuntu01:/$ lsb_release -a
No LSB modules are available.
Distributor ID:Ubuntu
Description:    Ubuntu 16.04.5 LTS
Release:          16.04
Codename:     xenial
```

### 🤔 Replication Case
I'm having this directory structure for my **azure** profile (I'm using direnv to load the environment variables, hence the .envrc in the tree):
```
├── azure
│   ├── controls
│   │   ├── resource_group.rb
│   │   └── subnet.rb
│   └── inspec.yml
└── .envrc
```

The content of **_azure/inspec.yml_**:
```
name: azure-compliance-profile
title: InSpec Profile
maintainer: Richard Diphoorn
copyright: Richard Diphoorn
copyright_email: n_a
license: Apache-2.0
summary: Azure Compliance Profile
version: 0.1.0
depends:
  - name: inspec-azure
    url: https://github.com/inspec/inspec-azure/archive/1.2.0.tar.gz
attributes:
  - name: location
    type: string
    default: northeurope
  - name: network_resource_group
    type: string
    default: TestNetwork
  - name: vnet_name
    type: string
    default: TestNetwork
  - name: subnet_name
    type: string
    default: TestSubnet
  - name: subnet_id
    type: string
  - name: subnet_address_prefix
    type: string
    default: 10.10.10.0/24
  - name: subnet_nsg
    default: TestNsg
```
The content of **_azure/controls/resource_group_**:
```
location        = attribute('location')
resource_group  = attribute('network_resource_group')
name            = attribute('subnet_name')
vnet            = attribute('vnet_name')
address_prefix  = attribute('subnet_address_prefix')
nsg             = attribute('subnet_nsg')

control 'check-if-resource-group-exists' do
  impact 1.0
  title 'Ensure Resource Group Exists'
  describe azurerm_resource_groups.where(name: resource_group) do
    it { should exist }
  end
end

control 'check-resource-group-properties' do
  impact 1.0
  title 'Ensure Resource Group properties are correct'
  describe azure_generic_resource(group_name: resource_group) do
    its('location') { should eq location }
    it { should have_tags }
    its('tag_count') { should be 2 }
  end
end
```

The content of **_azure/controls/subnet.rb_**:
```
location        = attribute('location')
resource_group  = attribute('network_resource_group')
name            = attribute('subnet_name')
vnet            = attribute('vnet_name')
address_prefix  = attribute('subnet_address_prefix')
nsg             = attribute('subnet_nsg')

control 'azurerm_subnet' do
  describe azurerm_subnet(resource_group: resource_group, vnet: vnet, name: name) do
    it                    { should exist }
    its('name')           { should eq name }
    its('type')           { should eq 'Microsoft.Network/virtualNetworks/subnets' }
    its('address_prefix') { should eq address_prefix }
    its('nsg')            { should eq nsg }
  end
end
```

The command is use to test:
`inspec exec azure -t azure://`
