### ISSUE TITLE
Getting error "undefined method `body' for nil:NilClass" when I am trying to test Azure Load Balancer with inspec using the API calls.

### ISSUE THREAD

**Issue by nsr99** [inspec/inspec-azure#206]
I am trying to test Azure Load Balancer with inspec using the API calls. My control file looks like below:

**Control file:**
```
control "file_check" do
    http_request = http('https://management.azure.com/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx/resourceGroups/myResourceGroupSLB/providers/Microsoft.Network/loadBalancers/myLoadBalancer/backendAddressPools/myBackendPool?api-version=2018-08-01',
                                    headers: {
                                        'Accept' => 'application/json',
                                        'Authorization' => 'Bearer <my-API-token>'
                                     })
    describe json(content: http_request.body) do
      its('name') { should eq 'hello' }
    end
end
```

**Profile file inspec.yml**
```
name: new_profile
title: Checking compliance of resources
license: Apache-2.0
summary: Inspec test for compliance
version: 1.0
inspec_version: '>= 2.1.81'
depends:
  - name: inspec-azure
    url: https://github.com/inspec/inspec-azure/archive/master.tar.gz
supports:
  - platform: azure
```

When running the test I am getting below error:

 **×  file_check: /home/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx/newtest/test/integration/new_profile/controls/basic.rb:13
     ×  Control Source Code Error /home/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx/new-test/test/integration/new_profile/controls/basic.rb:13
     undefined method `body' for nil:NilClass**

Seems like nothing is stored in http_request, Can anyone suggest where is the issue?

_Originally posted by @nsr99 in https://github.com/inspec/inspec/issues/2394#issuecomment-449693069_
