### ISSUE TITLE
Vault is not a class (TypeError)

### ISSUE THREAD

**Issue by DannyLee12** [inspec/inspec-azure#259]
Vault is not a class
---

Running inspec to check my azure config, get the following traceback:

```
➜ inspec exec . -t azure://
Traceback (most recent call last):
	22: from /usr/local/bin/inspec:199:in `<main>'
	21: from /usr/local/bin/inspec:199:in `load'
	20: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-bin-4.18.51/bin/inspec:11:in `<top (required)>'
	19: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.18.51/lib/inspec/base_cli.rb:35:in `start'
	18: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	17: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	16: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	15: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	14: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.18.51/lib/inspec/cli.rb:284:in `exec'
	13: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.18.51/lib/inspec/cli.rb:284:in `new'
	12: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.18.51/lib/inspec/runner.rb:78:in `initialize'
	11: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.18.51/lib/inspec/runner.rb:86:in `configure_transport'
	10: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.18.51/lib/inspec/backend.rb:46:in `create'
	 9: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.18.51/lib/inspec/config.rb:121:in `unpack_train_credentials'
	 8: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.18.51/lib/inspec/config.rb:146:in `_utc_merge_transport_options'
	 7: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/train-3.2.0/lib/train.rb:29:in `options'
	 6: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/train-3.2.0/lib/train.rb:45:in `load_transport'
	 5: from /opt/inspec/embedded/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 4: from /opt/inspec/embedded/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 3: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/train-3.2.0/lib/train/transports/azure.rb:12:in `<top (required)>'
	 2: from /opt/inspec/embedded/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 1: from /opt/inspec/embedded/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/train-3.2.0/lib/train/transports/clients/azure/vault.rb:7:in `<top (required)>': Vault is not a class (TypeError)
```

My profile looks like this:
```
name: verify
title: InSpec Profile
maintainer: The Authors
copyright: The Authors
copyright_email: you@example.com
license: Apache-2.0
summary: An InSpec Compliance Profile
version: 1.17.0
inspec_version: '>= 4.18.39'
depends:
  - name: inspec-azure
    git: https://github.com/inspec/inspec-azure.git
supports:
  platform: azure
```

## Possible Solution

I'm sure that there is something in the documentation that I have missed, but there is no nice example to check with. 

Otherwise this looks like there is a missing import somewhere. I may not have installed my plugins correctly, again looking for an example to work off of.

**Comment by rmoles** [comment]
Hi @DannyLee12, thanks for raising an issue.

One issue that I can see is that the depends statement is pointing at the inspec-azure git. This should be pointing to a release of inspec-azure similar to the example here: https://github.com/inspec/inspec-azure#create-a-new-profile
The available releases can be found here: https://github.com/inspec/inspec-azure/releases

Also please ensure that you are setting the required azure credentials as explained in the Getting started section of the README: https://github.com/inspec/inspec-azure#getting-started

Hopefully, this will get you past this issue 🤞

**Comment by DannyLee12** [comment]
Hi @rmoles 

Thanks for the assistance, I've updated my profile as instructed:
```
name: verify
title: InSpec Profile
maintainer: The Authors
copyright: The Authors
copyright_email: you@example.com
license: Apache-2.0
summary: An InSpec Compliance Profile
version: 0.1.0
depends:
  - name: inspec-azure
    url: https://github.com/inspec/inspec-azure/archive/v1.17.0.tar.gz
supports:
  platform: azure
```
But I still get the same issue.

I've also made sure that all my secrets are exported as explained. What else could I be missing?
