### ISSUE TITLE
Inspec YML and Azure resources - Inspec  is skipping my 'inspec-azure' profile

### ISSUE THREAD

**Issue by rohancollab** [inspec/inspec-azure#267]
I am not sure if I am including inspec azure resources correclty in my inspec-yml. Here is my inspec-yml

```yaml
name: my-profile
title: My own Azure profile
version: 1.0.0
depends:
    - name: inspec-azure
      git: https://github.com/inspec/inspec-azure.git
      supports:
       - platform-name: debian
```
here are my pipeline failures when I try to run the Inspec Azure tests 

$ inspec exec "Inspec-AzureTests"
[2020-07-17T03:18:58+00:00] WARN: Skipping profile: 'inspec-azure' on unsupported platform: 'debian/10.4'.
Profile: My own Azure profile (my-profile)
Version: 1.0.0
Target:  local://
  ×  azure-webapp-verification: Inspec-AzureTests/controls/azure-verify.rb:1
     ×  Control Source Code Error Inspec-AzureTests/controls/azure-verify.rb:1 
     undefined method `azurerm_webapp' for #<Inspec::Rule:0x000055a6b7e21f18>
Profile Summary: 0 successful controls, 1 control failure, 0 controls skipped
Test Summary: 0 successful, 1 failure, 0 skipped
ERROR: Job failed: exit code 1

 Also tried using 'supports' in inspec.yml as below 
```yaml
name: my-profile
title: My own Azure profile
version: 1.0.0
depends:
    - name: inspec-azure
      git: https://github.com/inspec/inspec-azure.git
      supports:
       - platform-name: debian
supports:
     - platform-name: debian

```
