### ISSUE TITLE
azure_generic_resource does not work with the resource_provider: set to 'Microsoft.Web/sites'

### ISSUE THREAD

**Issue by lhasadreams** [inspec/inspec-azure#302]
# Describe the problem
```
describe azure_generic_resource(resource_group: 'my_rg', name: 'my_name', resource_provider: 'Microsoft.Web/sites') do

    it { should exist }

    its('properties.kind') { should eq 'functionapp'}

    its('properties.state') { should eq 'Running' }

  end
```
When executed with InSpec against the Azure API you get:
`azure_generic_resource: . Unable to get the resource short description with the provided data:`

If you use the `resource_uri` instead then it functions as expected:
```
describe azure_generic_resource(resource_uri: '/resourceGroups/my_rg/providers/Microsoft.Web/sites', name: 'my_name', add_subscription_id: true) do

    it { should exist }

    its('properties.kind') { should eq 'functionapp'}

    its('properties.state') { should eq 'Running' }

  end
```

Using the latest Resource pack release and InSpec 4.23.4

**Comment by Sum123it** [comment]
Hi @rachelrice @omerdemirok - Which version of inspec did you use as `depends` to run this in `inspec.yml` . Does it require a lower version?

**Comment by omerdemirok** [comment]
@Sum123it, `v1.28.1` and onwards should be fine.

**Comment by Sum123it** [comment]
@omerdemirok - Probably this is an off topic- but I tried with below:

```
depends:
  - name: inspec-azure
    url: https://github.com/inspec/inspec-azure/archive/v1.28.1.tar.gz
```
But got below error:

```
         1: from /opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.18.51/lib/inspec/dsl.rb:68:in `method_missing'
/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.18.51/lib/inspec/dsl.rb:71:in `rescue in method_missing': undefined method `azure_generic_resources' for #<#<Class:0x000000000788d158>:0x000000000788c848> (NoMethodError)
Did you mean?  azure_resource_groups
```

**Comment by Sum123it** [comment]
Ok I tried with with `1.33.0`

```
Profile: InSpec Profile (automation-poc-sa511x)
Version: 0.1.0
Target:  azure://f5ae9b82-4fc1-4636-a861-8609a90524d2

  Azure Virtual Network : firstrt-eastus2-nprd-rg-01 Microsoft.Network/virtualNetworks eastus2-19761-nprd-vnet-01
     ×  Resource is failed due to undefined method `delete_suffix' for nil:NilClass

Profile: Azure Resource Pack (inspec-azure)
Version: 1.33.0
Target:  azure://f5ae9b82-4fc1-xxxxxxxxxxxxxxxxx

     No tests executed.

Test Summary: 0 successful, 1 failure, 0 skipped
```

got this above error.

**Comment by omerdemirok** [comment]
Hi @Sum123it, 
Can you provide,
- content of `inspec.lock`
- inspec version
- control
- the command running the profile

**Comment by Sum123it** [comment]
> Hi @Sum123it,
> Can you provide,
> 
> * content of `inspec.lock`
> * inspec version
> * control
> * the command running the profile

Hi @omerdemirok please see below:

```
lockfile_version: 1
depends:
- name: inspec-azure
  resolved_source:
    
    url: https://github.com/inspec/inspec-azure/archive/v1.33.0.tar.gz
```

```
sa511x@Azure:~$ inspec --version
4.18.51
```
below is my virtual network control and I ahave a few inputs taken from input.yml

```
app_name: xxxxx
xs_id: 'xxx'
environment: xxx
regixx: eastus2


#add all values in lowercase
Tags:
 - tags: env
 - tags: autxxxx
 - tags: Axxxx
 - tags: coxx_dl
 - tags: crxted_by
```
My `common_functions` has a few logic defined which are to validate few things.
```
require_relative 'common_functions'
application_name=input('application_name')
mots_id=input('mots_id')
environment=input('environment')
region=input('region')
arr_mandatory_tags=input('mandatory_Tags')
describe azurerm_virtual_network(resource_group: resource_group, name: vnet) do
    it                              { should exist }
    its('name')                       { should eq vnet }
    its('location')                   { should eq region }
    #its('type')                       { should eq 'Microsoft.Network/virtualNetworks' }
    #its('tags')       { should include 'created_by'}
    #its('tags')       { should include 'env' }
    #its('tags')       { should include 'mots_id' }
    #its('tags')       { should include 'contact_dl' }
    #its('tags')       { should include 'auto_fix' }  
    its('subnets')                   {should_not be_nil }
    #its('names')                    { should be_an(Array) }
    end
```

Command to run - 

`inspec exec azure-profile.sumit1.0.0 -t azure://f5ae9b82xxdxx --input-file /home/saxx/azure-profile.sumit1.0.0/input.yml`

PN: It works perfectly fine with v1.18.0. Though I wanted to add generic_resources with v1.33.0.

Now- none of my modules work and getting below error:

```
Profile: InSpec Profile (automation-poc)
Version: 0.1.0
Target:  azure://f5ae9b82-4xxxxxxx

  Azure Virtual Network : firstrt-eastus2-nprd-rg-01 Microsoft.Network/virtualNetworks eastus2-19761-nprd-vnet-01
     ×  Resource is failed due to undefined method `delete_suffix' for nil:NilClass

Profile: Azure Resource Pack (inspec-azure)
Version: 1.33.0
Target:  azure://f5axxxxxxxxx
```

inspec.yml as below:

```
inspec_version: '4.18.51'
depends:
  - name: inspec-azure
    url: https://github.com/inspec/inspec-azure/archive/v1.33.0.tar.gz

#  - name: inspec
#    url: https://github.com/inspec/inspec/archive/v4.21.3.tar.gz
    
supports:
  - platform: os
  - platform: azure
```
